name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: baswag/mypayslip
  DOCKERFILE_PATH: ./Dockerfile
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        dockerfile: ${{ env.DOCKERFILE_PATH }}
